### ISSUE TITLE
Replace inlined exception enum 

### ISSUE THREAD

**Issue by tmplt** [rtic-scope/itm-decode#11]
`itm_decode::ExceptionType` should be replaced with https://docs.rs/cortex-m/0.7.2/cortex_m/peripheral/scb/enum.Exception.html.

https://docs.rs/cortex-m/0.7.2/cortex_m/peripheral/scb/enum.VectActive.html may also be of interest.

**Comment by Yatekii** [comment]
Is it possible to build the cortex-m crate on x86?

**Comment by tmplt** [comment]
Possible with `default-features = false`.

Also, `ExceptionType` should be replaced with `VectActive` instead. We need to communicate the external interrupt number. But can we serde it if it lives in another crate?

**Comment by tmplt** [comment]
[Seems to be possible with some workaround.](https://serde.rs/remote-derive.html)
