### ISSUE TITLE
Consider adding Serialize, Deserialize to Itm structures.

### ISSUE THREAD

**Issue by Yatekii** [rtic-scope/itm-decode#4]
As the title says, this would be handy to also be able to send those packets over the network in string form.

**Comment by tmplt** [comment]
Is struct/enum serialization/deserialization a part of the standard library, or do we pull in serde for this?

**Comment by Yatekii** [comment]
We pull in serde for this. If you would like to keep the dependency count low, we can also make it optional.

**Comment by tmplt** [comment]
Yatekii <notifications@github.com> writes:
> we can also make it optional.
What's the praxis in the Rust ecosystem? Should crates enable every
feature OOTB or as little as possible?

**Comment by Yatekii** [comment]
I guess people have different opinions on that. Surely I, with my big Ryzen, care less than someone on an old mobile Intel :)

I think most people will make it a flag. It's no hassle and benefits folks that don't want it :)

**Comment by tmplt** [comment]
Added via feature "serde" in version 0.2.0. Disabled by default, following serde's own feature praxis.
