### ISSUE TITLE
Remove `anyhow`, `structopt` from lib dependencies

### ISSUE THREAD

**Issue by Urhengulas** [rtic-scope/itm-decode#7]
Hi @tmplt,

I'd appreciate if we could remove `anyhow` and `structopt` from the dependency tree of the library, since they are not required for it, but only the bin, as you also state in the `Cargo.toml`.

What do you think about this?

**Comment by tmplt** [comment]
Johann Hemmann <notifications@github.com> writes:
> What do you think about this?
Of course. But apparently there is no easy way to separate bin/lib
dependencies. See <https://github.com/rust-lang/cargo/issues/1982>. An
alternative is to split the crate in two, but I would prefer not to.

**Comment by Urhengulas** [comment]
> Johann Hemmann <notifications@github.com> writes:
> What do you think about this?
> Of course. But apparently there is no easy way to separate bin/lib dependencies. See <[rust-lang/cargo#1982](https://github.com/rust-lang/cargo/issues/1982)>. An alternative is to split the crate in two, but I would prefer not to.

I see that this is a bit more complicated than expected and understand that you'd like to keep the crates combined. I will think about a approach and propose it here 😄

**Comment by tmplt** [comment]
The crate shares the same name as the executable also, which may be
cause for trouble (it already is when generating documentation locally).
#8 would warrant a name-change on the crate.

**Comment by Urhengulas** [comment]
So what do you think of the idea of hiding the deps behind a cargo feature `bin`. This feature is enabled by default, but as a library user I can easily get rid of them by setting `default-features=false`.

See https://github.com/Urhengulas/itm-decode/commit/df9fe0426b6bcccb9d9af525370887897bbc7714

**Comment by tmplt** [comment]
LGTM. Create the PR and I'll merge it.
